ALTER TABLE Organizations ADD CONSTRAINT OrganiztionsPKey PRIMARY KEY (OrganizationID);
ALTER TABLE VideoGame ADD CONSTRAINT VideoGamePKey PRIMARY KEY (VideoGameID);
ALTER TABLE Player ADD CONSTRAINT PlayerPKey PRIMARY KEY (PlayerID);
ALTER TABLE ESportEvent ADD CONSTRAINT EventPKey PRIMARY KEY (EventId);
