BEGIN;

ALTER TABLE VideoGames ADD CONSTRAINT GameOrgFKey FOREIGN KEY (OrganisationID) REFERENCES Developers(OrganisationID) ON DELETE CASCADE;

ALTER TABLE Coaches ADD CONSTRAINT CoachTeamFKey FOREIGN KEY (TeamID) REFERENCES Teams(OrganisationID) ON DELETE CASCADE;
ALTER TABLE Coaches ADD CONSTRAINT CoachGameFKey FOREIGN KEY (GameID) REFERENCES VideoGames(GameID) ON DELETE CASCADE;

ALTER TABLE Played ADD CONSTRAINT PlayedOrgFKey FOREIGN KEY (OrganisationID) REFERENCES Teams(OrganisationID) ON DELETE CASCADE;
ALTER TABLE Played ADD CONSTRAINT PlayedEventFKey FOREIGN KEY (EventID) REFERENCES ESportEvents(EventID) ON DELETE CASCADE;
ALTER TABLE Played ADD CONSTRAINT PlayedPlayerFKey FOREIGN KEY (PlayerID) REFERENCES Players(PlayerID) ON DELETE CASCADE;
ALTER TABLE Played ADD CONSTRAINT PlayedGameFKey FOREIGN KEY (GameID) REFERENCES VideoGames(GameID) ON DELETE CASCADE;

ALTER TABLE Organised ADD CONSTRAINT OrganisedOrgFKey FOREIGN KEY (OrganisationID) REFERENCES Organisations(OrganisationID) ON DELETE CASCADE;
ALTER TABLE Organised ADD CONSTRAINT OrganisedEventFKey FOREIGN KEY (EventID) REFERENCES ESportEvents(EventID) ON DELETE CASCADE;

ALTER TABLE Ranklist ADD CONSTRAINT RankEventFKey FOREIGN KEY (EventID) REFERENCES ESportEvents(EventID) ON DELETE CASCADE;

ALTER TABLE Developers ADD CONSTRAINT DevOrgFKey FOREIGN KEY (OrganisationID) REFERENCES Organisations(OrganisationID) ON DELETE CASCADE;

ALTER TABLE Teams ADD CONSTRAINT TeamOrgFKey FOREIGN KEY (OrganisationID) REFERENCES Organisations(OrganisationID) ON DELETE CASCADE;

ALTER TABLE Owns ADD CONSTRAINT ParentOrgFKey FOREIGN KEY (ParentID) REFERENCES Organisations(OrganisationID) ON DELETE CASCADE;
ALTER TABLE Owns ADD CONSTRAINT SubsidiaryOrgFKey FOREIGN KEY (SubsidiaryID) REFERENCES Organisations(OrganisationID) ON DELETE CASCADE;

ALTER TABLE Platforms ADD CONSTRAINT PlatformGameFKey FOREIGN KEY (GameID) REFERENCES VideoGames(GameID) ON DELETE CASCADE;

COMMIT;
